server:
  servlet:
    context-path: /duet
  port: 9999

logging:
  level:
    root: INFO

spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 5MB
  application:
    name: demo
  #redis:
    #database: 0      # Redis数据库索引（默认为0）
    #host: localhost  # Redis服务器地址
    #port: 6379       # Redis服务器连接端口
    #password:        # Redis服务器连接密码（默认为空）
    #timeout: 5000    # 连接超时时间（毫秒）
    #jedis: 
      #pool:
        #max-active: 100  # 连接池最大连接数（使用负值表示没有限制）
        #max-idle: 10     # 连接池中的最大空闲连接
        #max-wait: -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
        #min-idle: 10     # 连接池中的最小空闲连接  
  # json 转化移除 null 字段
  # jackson:
  #   default-property-inclusion: non_null
  datasource:
    # 启动时自动运行的 SQL 文件
    # schema: classpath:init-sql/schema.sql
    # continue-on-error: true
    druid:
      url: jdbc:mysql://localhost:3306/duet?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: root
      #password: aozmQtqh
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 连接池配置
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: fasle
        login-username: user
        login-password: password
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000
          merge-sql: true
# mybatis 配置
mybatis:
  mapper-locations: classpath:/com/brt/duet/dao/*/*Dao.xml,/com/brt/duet/dao/*Dao.xml
  # 配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性
  configuration:
    map-underscore-to-camel-case: true
# PageHelper 配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  
oss:
  accessKeyId: -
  accessKeySecret: -
  endpoint: -
  bucket: -
  url: -
  filesize: 5242880
  imagesize: 5242880
